DROP TABLE IF
 EXISTS Audit_Item;

DROP TABLE IF
 EXISTS Items;

CREATE TABLE IF NOT EXISTS Items(
  id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
  name          VARCHAR (40) NOT NULL,
  unique_number VARCHAR(63)  NOT NULL UNIQUE,
  description   VARCHAR(100) NOT NULL,
  status        VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS Audit_Item(
  id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
  action          VARCHAR (10) NOT NULL,
  item_id         BIGINT UNSIGNED  NOT NULL,
  update_Status   VARCHAR(10) NOT NULL,
  date DATETIME   NOT NULL
);
